fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:  App\Entity\User
    use_username_form_type: true
    from_email:
        address:        '%env(APP_MAILER_FROM_EMAIL)%'
        sender_name:    '%env(APP_MAILER_FROM_NAME)%'
    profile:
        form:
            type: App\Form\Type\ProfileFormType
    service:
        mailer: App\FOSUB\Mailer
