nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['*']
        max_age: 3600
    paths:
        '^/packages/list\.json$':
            allow_methods: ['GET']
            forced_allow_origin_value: '*'
        '^/search\.json$':
            allow_methods: ['GET']
        '^/packages/[^/]+/[^/]+\.json$':
            allow_methods: ['GET']
            forced_allow_origin_value: '*'
