# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
        - HWI\Bundle\OAuthBundle\Security\Core\Authentication\Token\OAuthToken

    backup_codes:
        enabled: true
        manager: App\Security\TwoFactorAuthManager

    totp:
        enabled: true
        server_name: '%env(APP_HOSTNAME)%'
        issuer: Packagist
        window: 1

    trusted_device:
        enabled: true
        lifetime: 2592000 # 30 days
