language: php
dist: xenial
sudo: false

env:
  global:
    secure: "ejwL5+8AWrlcno3bSOfLNgNEGe6Kdegk19dr/It4QCZDw9Vs5nmuUq3e7sZ0+CSLVoo5q3L1Zs0YbkDdgkFA8Z2zWyhWxNjIWx+qb1aDh7ffSSileVRiw8ReQ14GiXxGTi0V5zR2zNwY5KdJNor0CsV8hOgZmFz6/qEUzXWY9Kw="

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server
  - mysql

php:
  - 7.4

matrix:
  fast_finish: true

before_install:
    - 'echo "APP_GITHUB_CLIENT_ID=$GH_CLIENT_ID" >> .env.local'
    - 'echo "APP_GITHUB_CLIENT_SECRET=$GH_CLIENT_SECRET" >> .env.local'

install:
    - composer install

before_script:
    - app/console doctrine:database:create --env=test -n
    - app/console doctrine:schema:create --env=test -n

script:
    - vendor/bin/phpunit

git:
  depth: 5
