services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            # services
            $redis: '@snc_redis.default_client'

    App\Service\Scheduler:
        public: true

